#!/bin/bash

cur_dir=`pwd`
[ -d $HOME/.vim/bundle/Vundle.vim ] || git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim

# Check if were also install config for awesome wm
#if [[ "$*" == "awesome" ]]
#then
#    install_awesome="Y"
#    awesome_path=$HOME/".config/awesome"
#    if [ -f $awesome_path/rc.lua ]
#    then
#        mv $awesome_path/rc.lua $awesome_path/rc.lua.vanilla
#    else
#        mkdir -p $awesome_path
#    fi
#fi
ln --backup=numbered -s $cur_dir/bashrc $HOME/.bashrc
ln --backup=numbered -s $cur_dir/vimrc $HOME/.vimrc
ln --backup=numbered -s $cur_dir/gitconfig $HOME/.gitconfig

if [ "$install_awesome" = "Y" ]
then
    ln -s rc.lua $awesome_path/rc.lua
fi

# my vimrc requires 2 non-standard dirs
[ -d $HOME/.vim/backup ] || mkdir -p $HOME/.vim/backup
[ -d $HOME/.vim/tmp ] || mkdir -p $HOME/.vim/tmp

vim +PluginInstall +qall
